apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: ./schema
  contents:
  - path: vendor
    git:
      url: https://github.com/GaloyMoney/cala-enterprise.git
      ref: main
    includePaths:
    - schema.graphql
