// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"

	"github.com/Khan/genqlient/graphql"
)

type AccountCreateInput struct {
	AccountId         string           `json:"accountId"`
	ExternalId        *string          `json:"externalId"`
	Code              string           `json:"code"`
	Name              string           `json:"name"`
	NormalBalanceType DebitOrCredit    `json:"normalBalanceType"`
	Description       *string          `json:"description"`
	Status            Status           `json:"status"`
	Metadata          *json.RawMessage `json:"metadata"`
	AccountSetIds     []string         `json:"accountSetIds"`
}

// GetAccountId returns AccountCreateInput.AccountId, and is useful for accessing the field via an interface.
func (v *AccountCreateInput) GetAccountId() string { return v.AccountId }

// GetExternalId returns AccountCreateInput.ExternalId, and is useful for accessing the field via an interface.
func (v *AccountCreateInput) GetExternalId() *string { return v.ExternalId }

// GetCode returns AccountCreateInput.Code, and is useful for accessing the field via an interface.
func (v *AccountCreateInput) GetCode() string { return v.Code }

// GetName returns AccountCreateInput.Name, and is useful for accessing the field via an interface.
func (v *AccountCreateInput) GetName() string { return v.Name }

// GetNormalBalanceType returns AccountCreateInput.NormalBalanceType, and is useful for accessing the field via an interface.
func (v *AccountCreateInput) GetNormalBalanceType() DebitOrCredit { return v.NormalBalanceType }

// GetDescription returns AccountCreateInput.Description, and is useful for accessing the field via an interface.
func (v *AccountCreateInput) GetDescription() *string { return v.Description }

// GetStatus returns AccountCreateInput.Status, and is useful for accessing the field via an interface.
func (v *AccountCreateInput) GetStatus() Status { return v.Status }

// GetMetadata returns AccountCreateInput.Metadata, and is useful for accessing the field via an interface.
func (v *AccountCreateInput) GetMetadata() *json.RawMessage { return v.Metadata }

// GetAccountSetIds returns AccountCreateInput.AccountSetIds, and is useful for accessing the field via an interface.
func (v *AccountCreateInput) GetAccountSetIds() []string { return v.AccountSetIds }

type AccountSetCreateInput struct {
	AccountSetId      string           `json:"accountSetId"`
	JournalId         string           `json:"journalId"`
	Name              string           `json:"name"`
	NormalBalanceType DebitOrCredit    `json:"normalBalanceType"`
	Description       *string          `json:"description"`
	Metadata          *json.RawMessage `json:"metadata"`
}

// GetAccountSetId returns AccountSetCreateInput.AccountSetId, and is useful for accessing the field via an interface.
func (v *AccountSetCreateInput) GetAccountSetId() string { return v.AccountSetId }

// GetJournalId returns AccountSetCreateInput.JournalId, and is useful for accessing the field via an interface.
func (v *AccountSetCreateInput) GetJournalId() string { return v.JournalId }

// GetName returns AccountSetCreateInput.Name, and is useful for accessing the field via an interface.
func (v *AccountSetCreateInput) GetName() string { return v.Name }

// GetNormalBalanceType returns AccountSetCreateInput.NormalBalanceType, and is useful for accessing the field via an interface.
func (v *AccountSetCreateInput) GetNormalBalanceType() DebitOrCredit { return v.NormalBalanceType }

// GetDescription returns AccountSetCreateInput.Description, and is useful for accessing the field via an interface.
func (v *AccountSetCreateInput) GetDescription() *string { return v.Description }

// GetMetadata returns AccountSetCreateInput.Metadata, and is useful for accessing the field via an interface.
func (v *AccountSetCreateInput) GetMetadata() *json.RawMessage { return v.Metadata }

type BalanceSheetCreateInput struct {
	JournalId string `json:"journalId"`
}

// GetJournalId returns BalanceSheetCreateInput.JournalId, and is useful for accessing the field via an interface.
func (v *BalanceSheetCreateInput) GetJournalId() string { return v.JournalId }

type BfxIntegrationCreateInput struct {
	IntegrationId string  `json:"integrationId"`
	Name          string  `json:"name"`
	Description   *string `json:"description"`
	JournalId     string  `json:"journalId"`
	Key           string  `json:"key"`
	Secret        string  `json:"secret"`
}

// GetIntegrationId returns BfxIntegrationCreateInput.IntegrationId, and is useful for accessing the field via an interface.
func (v *BfxIntegrationCreateInput) GetIntegrationId() string { return v.IntegrationId }

// GetName returns BfxIntegrationCreateInput.Name, and is useful for accessing the field via an interface.
func (v *BfxIntegrationCreateInput) GetName() string { return v.Name }

// GetDescription returns BfxIntegrationCreateInput.Description, and is useful for accessing the field via an interface.
func (v *BfxIntegrationCreateInput) GetDescription() *string { return v.Description }

// GetJournalId returns BfxIntegrationCreateInput.JournalId, and is useful for accessing the field via an interface.
func (v *BfxIntegrationCreateInput) GetJournalId() string { return v.JournalId }

// GetKey returns BfxIntegrationCreateInput.Key, and is useful for accessing the field via an interface.
func (v *BfxIntegrationCreateInput) GetKey() string { return v.Key }

// GetSecret returns BfxIntegrationCreateInput.Secret, and is useful for accessing the field via an interface.
func (v *BfxIntegrationCreateInput) GetSecret() string { return v.Secret }

type DebitOrCredit string

const (
	DebitOrCreditDebit  DebitOrCredit = "DEBIT"
	DebitOrCreditCredit DebitOrCredit = "CREDIT"
)

type JournalCreateInput struct {
	JournalId   string  `json:"journalId"`
	Name        string  `json:"name"`
	Status      Status  `json:"status"`
	Description *string `json:"description"`
}

// GetJournalId returns JournalCreateInput.JournalId, and is useful for accessing the field via an interface.
func (v *JournalCreateInput) GetJournalId() string { return v.JournalId }

// GetName returns JournalCreateInput.Name, and is useful for accessing the field via an interface.
func (v *JournalCreateInput) GetName() string { return v.Name }

// GetStatus returns JournalCreateInput.Status, and is useful for accessing the field via an interface.
func (v *JournalCreateInput) GetStatus() Status { return v.Status }

// GetDescription returns JournalCreateInput.Description, and is useful for accessing the field via an interface.
func (v *JournalCreateInput) GetDescription() *string { return v.Description }

type Status string

const (
	StatusActive Status = "ACTIVE"
	StatusLocked Status = "LOCKED"
)

// __accountCreateInput is used internally by genqlient
type __accountCreateInput struct {
	Input AccountCreateInput `json:"input"`
}

// GetInput returns __accountCreateInput.Input, and is useful for accessing the field via an interface.
func (v *__accountCreateInput) GetInput() AccountCreateInput { return v.Input }

// __accountGetInput is used internally by genqlient
type __accountGetInput struct {
	Id string `json:"id"`
}

// GetId returns __accountGetInput.Id, and is useful for accessing the field via an interface.
func (v *__accountGetInput) GetId() string { return v.Id }

// __accountSetCreateInput is used internally by genqlient
type __accountSetCreateInput struct {
	Input AccountSetCreateInput `json:"input"`
}

// GetInput returns __accountSetCreateInput.Input, and is useful for accessing the field via an interface.
func (v *__accountSetCreateInput) GetInput() AccountSetCreateInput { return v.Input }

// __accountSetGetInput is used internally by genqlient
type __accountSetGetInput struct {
	Id string `json:"id"`
}

// GetId returns __accountSetGetInput.Id, and is useful for accessing the field via an interface.
func (v *__accountSetGetInput) GetId() string { return v.Id }

// __accountSetMemberAccountCreateInput is used internally by genqlient
type __accountSetMemberAccountCreateInput struct {
	AccountSetId string `json:"accountSetId"`
	AccountId    string `json:"accountId"`
}

// GetAccountSetId returns __accountSetMemberAccountCreateInput.AccountSetId, and is useful for accessing the field via an interface.
func (v *__accountSetMemberAccountCreateInput) GetAccountSetId() string { return v.AccountSetId }

// GetAccountId returns __accountSetMemberAccountCreateInput.AccountId, and is useful for accessing the field via an interface.
func (v *__accountSetMemberAccountCreateInput) GetAccountId() string { return v.AccountId }

// __accountSetMemberAccountRemoveInput is used internally by genqlient
type __accountSetMemberAccountRemoveInput struct {
	AccountSetId string `json:"accountSetId"`
	AccountId    string `json:"accountId"`
}

// GetAccountSetId returns __accountSetMemberAccountRemoveInput.AccountSetId, and is useful for accessing the field via an interface.
func (v *__accountSetMemberAccountRemoveInput) GetAccountSetId() string { return v.AccountSetId }

// GetAccountId returns __accountSetMemberAccountRemoveInput.AccountId, and is useful for accessing the field via an interface.
func (v *__accountSetMemberAccountRemoveInput) GetAccountId() string { return v.AccountId }

// __accountSetMemberAccountSetCreateInput is used internally by genqlient
type __accountSetMemberAccountSetCreateInput struct {
	AccountSetId       string `json:"accountSetId"`
	MemberAccountSetId string `json:"memberAccountSetId"`
}

// GetAccountSetId returns __accountSetMemberAccountSetCreateInput.AccountSetId, and is useful for accessing the field via an interface.
func (v *__accountSetMemberAccountSetCreateInput) GetAccountSetId() string { return v.AccountSetId }

// GetMemberAccountSetId returns __accountSetMemberAccountSetCreateInput.MemberAccountSetId, and is useful for accessing the field via an interface.
func (v *__accountSetMemberAccountSetCreateInput) GetMemberAccountSetId() string {
	return v.MemberAccountSetId
}

// __accountSetMemberAccountSetRemoveInput is used internally by genqlient
type __accountSetMemberAccountSetRemoveInput struct {
	AccountSetId       string `json:"accountSetId"`
	MemberAccountSetId string `json:"memberAccountSetId"`
}

// GetAccountSetId returns __accountSetMemberAccountSetRemoveInput.AccountSetId, and is useful for accessing the field via an interface.
func (v *__accountSetMemberAccountSetRemoveInput) GetAccountSetId() string { return v.AccountSetId }

// GetMemberAccountSetId returns __accountSetMemberAccountSetRemoveInput.MemberAccountSetId, and is useful for accessing the field via an interface.
func (v *__accountSetMemberAccountSetRemoveInput) GetMemberAccountSetId() string {
	return v.MemberAccountSetId
}

// __balanceSheetCreateInput is used internally by genqlient
type __balanceSheetCreateInput struct {
	Input BalanceSheetCreateInput `json:"input"`
}

// GetInput returns __balanceSheetCreateInput.Input, and is useful for accessing the field via an interface.
func (v *__balanceSheetCreateInput) GetInput() BalanceSheetCreateInput { return v.Input }

// __balanceSheetGetInput is used internally by genqlient
type __balanceSheetGetInput struct {
	JournalId string `json:"journalId"`
}

// GetJournalId returns __balanceSheetGetInput.JournalId, and is useful for accessing the field via an interface.
func (v *__balanceSheetGetInput) GetJournalId() string { return v.JournalId }

// __bfxIntegrationCreateInput is used internally by genqlient
type __bfxIntegrationCreateInput struct {
	Input BfxIntegrationCreateInput `json:"input"`
}

// GetInput returns __bfxIntegrationCreateInput.Input, and is useful for accessing the field via an interface.
func (v *__bfxIntegrationCreateInput) GetInput() BfxIntegrationCreateInput { return v.Input }

// __bfxIntegrationGetInput is used internally by genqlient
type __bfxIntegrationGetInput struct {
	Id string `json:"id"`
}

// GetId returns __bfxIntegrationGetInput.Id, and is useful for accessing the field via an interface.
func (v *__bfxIntegrationGetInput) GetId() string { return v.Id }

// __journalCreateInput is used internally by genqlient
type __journalCreateInput struct {
	Input JournalCreateInput `json:"input"`
}

// GetInput returns __journalCreateInput.Input, and is useful for accessing the field via an interface.
func (v *__journalCreateInput) GetInput() JournalCreateInput { return v.Input }

// accountCreateAccountCreateAccountCreatePayload includes the requested fields of the GraphQL type AccountCreatePayload.
type accountCreateAccountCreateAccountCreatePayload struct {
	Account accountCreateAccountCreateAccountCreatePayloadAccount `json:"account"`
}

// GetAccount returns accountCreateAccountCreateAccountCreatePayload.Account, and is useful for accessing the field via an interface.
func (v *accountCreateAccountCreateAccountCreatePayload) GetAccount() accountCreateAccountCreateAccountCreatePayloadAccount {
	return v.Account
}

// accountCreateAccountCreateAccountCreatePayloadAccount includes the requested fields of the GraphQL type Account.
type accountCreateAccountCreateAccountCreatePayloadAccount struct {
	AccountId         string           `json:"accountId"`
	Code              string           `json:"code"`
	Name              string           `json:"name"`
	NormalBalanceType DebitOrCredit    `json:"normalBalanceType"`
	Status            Status           `json:"status"`
	ExternalId        *string          `json:"externalId"`
	Description       *string          `json:"description"`
	Metadata          *json.RawMessage `json:"metadata"`
}

// GetAccountId returns accountCreateAccountCreateAccountCreatePayloadAccount.AccountId, and is useful for accessing the field via an interface.
func (v *accountCreateAccountCreateAccountCreatePayloadAccount) GetAccountId() string {
	return v.AccountId
}

// GetCode returns accountCreateAccountCreateAccountCreatePayloadAccount.Code, and is useful for accessing the field via an interface.
func (v *accountCreateAccountCreateAccountCreatePayloadAccount) GetCode() string { return v.Code }

// GetName returns accountCreateAccountCreateAccountCreatePayloadAccount.Name, and is useful for accessing the field via an interface.
func (v *accountCreateAccountCreateAccountCreatePayloadAccount) GetName() string { return v.Name }

// GetNormalBalanceType returns accountCreateAccountCreateAccountCreatePayloadAccount.NormalBalanceType, and is useful for accessing the field via an interface.
func (v *accountCreateAccountCreateAccountCreatePayloadAccount) GetNormalBalanceType() DebitOrCredit {
	return v.NormalBalanceType
}

// GetStatus returns accountCreateAccountCreateAccountCreatePayloadAccount.Status, and is useful for accessing the field via an interface.
func (v *accountCreateAccountCreateAccountCreatePayloadAccount) GetStatus() Status { return v.Status }

// GetExternalId returns accountCreateAccountCreateAccountCreatePayloadAccount.ExternalId, and is useful for accessing the field via an interface.
func (v *accountCreateAccountCreateAccountCreatePayloadAccount) GetExternalId() *string {
	return v.ExternalId
}

// GetDescription returns accountCreateAccountCreateAccountCreatePayloadAccount.Description, and is useful for accessing the field via an interface.
func (v *accountCreateAccountCreateAccountCreatePayloadAccount) GetDescription() *string {
	return v.Description
}

// GetMetadata returns accountCreateAccountCreateAccountCreatePayloadAccount.Metadata, and is useful for accessing the field via an interface.
func (v *accountCreateAccountCreateAccountCreatePayloadAccount) GetMetadata() *json.RawMessage {
	return v.Metadata
}

// accountCreateResponse is returned by accountCreate on success.
type accountCreateResponse struct {
	AccountCreate accountCreateAccountCreateAccountCreatePayload `json:"accountCreate"`
}

// GetAccountCreate returns accountCreateResponse.AccountCreate, and is useful for accessing the field via an interface.
func (v *accountCreateResponse) GetAccountCreate() accountCreateAccountCreateAccountCreatePayload {
	return v.AccountCreate
}

// accountGetAccount includes the requested fields of the GraphQL type Account.
type accountGetAccount struct {
	AccountId         string                                    `json:"accountId"`
	Name              string                                    `json:"name"`
	Description       *string                                   `json:"description"`
	Status            Status                                    `json:"status"`
	Metadata          *json.RawMessage                          `json:"metadata"`
	Code              string                                    `json:"code"`
	NormalBalanceType DebitOrCredit                             `json:"normalBalanceType"`
	ExternalId        *string                                   `json:"externalId"`
	Sets              accountGetAccountSetsAccountSetConnection `json:"sets"`
}

// GetAccountId returns accountGetAccount.AccountId, and is useful for accessing the field via an interface.
func (v *accountGetAccount) GetAccountId() string { return v.AccountId }

// GetName returns accountGetAccount.Name, and is useful for accessing the field via an interface.
func (v *accountGetAccount) GetName() string { return v.Name }

// GetDescription returns accountGetAccount.Description, and is useful for accessing the field via an interface.
func (v *accountGetAccount) GetDescription() *string { return v.Description }

// GetStatus returns accountGetAccount.Status, and is useful for accessing the field via an interface.
func (v *accountGetAccount) GetStatus() Status { return v.Status }

// GetMetadata returns accountGetAccount.Metadata, and is useful for accessing the field via an interface.
func (v *accountGetAccount) GetMetadata() *json.RawMessage { return v.Metadata }

// GetCode returns accountGetAccount.Code, and is useful for accessing the field via an interface.
func (v *accountGetAccount) GetCode() string { return v.Code }

// GetNormalBalanceType returns accountGetAccount.NormalBalanceType, and is useful for accessing the field via an interface.
func (v *accountGetAccount) GetNormalBalanceType() DebitOrCredit { return v.NormalBalanceType }

// GetExternalId returns accountGetAccount.ExternalId, and is useful for accessing the field via an interface.
func (v *accountGetAccount) GetExternalId() *string { return v.ExternalId }

// GetSets returns accountGetAccount.Sets, and is useful for accessing the field via an interface.
func (v *accountGetAccount) GetSets() accountGetAccountSetsAccountSetConnection { return v.Sets }

// accountGetAccountSetsAccountSetConnection includes the requested fields of the GraphQL type AccountSetConnection.
type accountGetAccountSetsAccountSetConnection struct {
	// A list of nodes.
	Nodes []accountGetAccountSetsAccountSetConnectionNodesAccountSet `json:"nodes"`
}

// GetNodes returns accountGetAccountSetsAccountSetConnection.Nodes, and is useful for accessing the field via an interface.
func (v *accountGetAccountSetsAccountSetConnection) GetNodes() []accountGetAccountSetsAccountSetConnectionNodesAccountSet {
	return v.Nodes
}

// accountGetAccountSetsAccountSetConnectionNodesAccountSet includes the requested fields of the GraphQL type AccountSet.
type accountGetAccountSetsAccountSetConnectionNodesAccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns accountGetAccountSetsAccountSetConnectionNodesAccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *accountGetAccountSetsAccountSetConnectionNodesAccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// accountGetResponse is returned by accountGet on success.
type accountGetResponse struct {
	Account *accountGetAccount `json:"account"`
}

// GetAccount returns accountGetResponse.Account, and is useful for accessing the field via an interface.
func (v *accountGetResponse) GetAccount() *accountGetAccount { return v.Account }

// accountSetCreateAccountSetCreateAccountSetCreatePayload includes the requested fields of the GraphQL type AccountSetCreatePayload.
type accountSetCreateAccountSetCreateAccountSetCreatePayload struct {
	AccountSet accountSetCreateAccountSetCreateAccountSetCreatePayloadAccountSet `json:"accountSet"`
}

// GetAccountSet returns accountSetCreateAccountSetCreateAccountSetCreatePayload.AccountSet, and is useful for accessing the field via an interface.
func (v *accountSetCreateAccountSetCreateAccountSetCreatePayload) GetAccountSet() accountSetCreateAccountSetCreateAccountSetCreatePayloadAccountSet {
	return v.AccountSet
}

// accountSetCreateAccountSetCreateAccountSetCreatePayloadAccountSet includes the requested fields of the GraphQL type AccountSet.
type accountSetCreateAccountSetCreateAccountSetCreatePayloadAccountSet struct {
	AccountSetId      string           `json:"accountSetId"`
	JournalId         string           `json:"journalId"`
	Name              string           `json:"name"`
	NormalBalanceType DebitOrCredit    `json:"normalBalanceType"`
	Description       *string          `json:"description"`
	Metadata          *json.RawMessage `json:"metadata"`
}

// GetAccountSetId returns accountSetCreateAccountSetCreateAccountSetCreatePayloadAccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *accountSetCreateAccountSetCreateAccountSetCreatePayloadAccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// GetJournalId returns accountSetCreateAccountSetCreateAccountSetCreatePayloadAccountSet.JournalId, and is useful for accessing the field via an interface.
func (v *accountSetCreateAccountSetCreateAccountSetCreatePayloadAccountSet) GetJournalId() string {
	return v.JournalId
}

// GetName returns accountSetCreateAccountSetCreateAccountSetCreatePayloadAccountSet.Name, and is useful for accessing the field via an interface.
func (v *accountSetCreateAccountSetCreateAccountSetCreatePayloadAccountSet) GetName() string {
	return v.Name
}

// GetNormalBalanceType returns accountSetCreateAccountSetCreateAccountSetCreatePayloadAccountSet.NormalBalanceType, and is useful for accessing the field via an interface.
func (v *accountSetCreateAccountSetCreateAccountSetCreatePayloadAccountSet) GetNormalBalanceType() DebitOrCredit {
	return v.NormalBalanceType
}

// GetDescription returns accountSetCreateAccountSetCreateAccountSetCreatePayloadAccountSet.Description, and is useful for accessing the field via an interface.
func (v *accountSetCreateAccountSetCreateAccountSetCreatePayloadAccountSet) GetDescription() *string {
	return v.Description
}

// GetMetadata returns accountSetCreateAccountSetCreateAccountSetCreatePayloadAccountSet.Metadata, and is useful for accessing the field via an interface.
func (v *accountSetCreateAccountSetCreateAccountSetCreatePayloadAccountSet) GetMetadata() *json.RawMessage {
	return v.Metadata
}

// accountSetCreateResponse is returned by accountSetCreate on success.
type accountSetCreateResponse struct {
	AccountSetCreate accountSetCreateAccountSetCreateAccountSetCreatePayload `json:"accountSetCreate"`
}

// GetAccountSetCreate returns accountSetCreateResponse.AccountSetCreate, and is useful for accessing the field via an interface.
func (v *accountSetCreateResponse) GetAccountSetCreate() accountSetCreateAccountSetCreateAccountSetCreatePayload {
	return v.AccountSetCreate
}

// accountSetGetAccountSet includes the requested fields of the GraphQL type AccountSet.
type accountSetGetAccountSet struct {
	AccountSetId      string        `json:"accountSetId"`
	JournalId         string        `json:"journalId"`
	Name              string        `json:"name"`
	Description       *string       `json:"description"`
	NormalBalanceType DebitOrCredit `json:"normalBalanceType"`
}

// GetAccountSetId returns accountSetGetAccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *accountSetGetAccountSet) GetAccountSetId() string { return v.AccountSetId }

// GetJournalId returns accountSetGetAccountSet.JournalId, and is useful for accessing the field via an interface.
func (v *accountSetGetAccountSet) GetJournalId() string { return v.JournalId }

// GetName returns accountSetGetAccountSet.Name, and is useful for accessing the field via an interface.
func (v *accountSetGetAccountSet) GetName() string { return v.Name }

// GetDescription returns accountSetGetAccountSet.Description, and is useful for accessing the field via an interface.
func (v *accountSetGetAccountSet) GetDescription() *string { return v.Description }

// GetNormalBalanceType returns accountSetGetAccountSet.NormalBalanceType, and is useful for accessing the field via an interface.
func (v *accountSetGetAccountSet) GetNormalBalanceType() DebitOrCredit { return v.NormalBalanceType }

// accountSetGetResponse is returned by accountSetGet on success.
type accountSetGetResponse struct {
	AccountSet *accountSetGetAccountSet `json:"accountSet"`
}

// GetAccountSet returns accountSetGetResponse.AccountSet, and is useful for accessing the field via an interface.
func (v *accountSetGetResponse) GetAccountSet() *accountSetGetAccountSet { return v.AccountSet }

// accountSetMemberAccountCreateAddToAccountSetAddToAccountSetPayload includes the requested fields of the GraphQL type AddToAccountSetPayload.
type accountSetMemberAccountCreateAddToAccountSetAddToAccountSetPayload struct {
	AccountSet accountSetMemberAccountCreateAddToAccountSetAddToAccountSetPayloadAccountSet `json:"accountSet"`
}

// GetAccountSet returns accountSetMemberAccountCreateAddToAccountSetAddToAccountSetPayload.AccountSet, and is useful for accessing the field via an interface.
func (v *accountSetMemberAccountCreateAddToAccountSetAddToAccountSetPayload) GetAccountSet() accountSetMemberAccountCreateAddToAccountSetAddToAccountSetPayloadAccountSet {
	return v.AccountSet
}

// accountSetMemberAccountCreateAddToAccountSetAddToAccountSetPayloadAccountSet includes the requested fields of the GraphQL type AccountSet.
type accountSetMemberAccountCreateAddToAccountSetAddToAccountSetPayloadAccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns accountSetMemberAccountCreateAddToAccountSetAddToAccountSetPayloadAccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *accountSetMemberAccountCreateAddToAccountSetAddToAccountSetPayloadAccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// accountSetMemberAccountCreateResponse is returned by accountSetMemberAccountCreate on success.
type accountSetMemberAccountCreateResponse struct {
	AddToAccountSet accountSetMemberAccountCreateAddToAccountSetAddToAccountSetPayload `json:"addToAccountSet"`
}

// GetAddToAccountSet returns accountSetMemberAccountCreateResponse.AddToAccountSet, and is useful for accessing the field via an interface.
func (v *accountSetMemberAccountCreateResponse) GetAddToAccountSet() accountSetMemberAccountCreateAddToAccountSetAddToAccountSetPayload {
	return v.AddToAccountSet
}

// accountSetMemberAccountRemoveRemoveFromAccountSetRemoveFromAccountSetPayload includes the requested fields of the GraphQL type RemoveFromAccountSetPayload.
type accountSetMemberAccountRemoveRemoveFromAccountSetRemoveFromAccountSetPayload struct {
	AccountSet accountSetMemberAccountRemoveRemoveFromAccountSetRemoveFromAccountSetPayloadAccountSet `json:"accountSet"`
}

// GetAccountSet returns accountSetMemberAccountRemoveRemoveFromAccountSetRemoveFromAccountSetPayload.AccountSet, and is useful for accessing the field via an interface.
func (v *accountSetMemberAccountRemoveRemoveFromAccountSetRemoveFromAccountSetPayload) GetAccountSet() accountSetMemberAccountRemoveRemoveFromAccountSetRemoveFromAccountSetPayloadAccountSet {
	return v.AccountSet
}

// accountSetMemberAccountRemoveRemoveFromAccountSetRemoveFromAccountSetPayloadAccountSet includes the requested fields of the GraphQL type AccountSet.
type accountSetMemberAccountRemoveRemoveFromAccountSetRemoveFromAccountSetPayloadAccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns accountSetMemberAccountRemoveRemoveFromAccountSetRemoveFromAccountSetPayloadAccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *accountSetMemberAccountRemoveRemoveFromAccountSetRemoveFromAccountSetPayloadAccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// accountSetMemberAccountRemoveResponse is returned by accountSetMemberAccountRemove on success.
type accountSetMemberAccountRemoveResponse struct {
	RemoveFromAccountSet accountSetMemberAccountRemoveRemoveFromAccountSetRemoveFromAccountSetPayload `json:"removeFromAccountSet"`
}

// GetRemoveFromAccountSet returns accountSetMemberAccountRemoveResponse.RemoveFromAccountSet, and is useful for accessing the field via an interface.
func (v *accountSetMemberAccountRemoveResponse) GetRemoveFromAccountSet() accountSetMemberAccountRemoveRemoveFromAccountSetRemoveFromAccountSetPayload {
	return v.RemoveFromAccountSet
}

// accountSetMemberAccountSetCreateAddToAccountSetAddToAccountSetPayload includes the requested fields of the GraphQL type AddToAccountSetPayload.
type accountSetMemberAccountSetCreateAddToAccountSetAddToAccountSetPayload struct {
	AccountSet accountSetMemberAccountSetCreateAddToAccountSetAddToAccountSetPayloadAccountSet `json:"accountSet"`
}

// GetAccountSet returns accountSetMemberAccountSetCreateAddToAccountSetAddToAccountSetPayload.AccountSet, and is useful for accessing the field via an interface.
func (v *accountSetMemberAccountSetCreateAddToAccountSetAddToAccountSetPayload) GetAccountSet() accountSetMemberAccountSetCreateAddToAccountSetAddToAccountSetPayloadAccountSet {
	return v.AccountSet
}

// accountSetMemberAccountSetCreateAddToAccountSetAddToAccountSetPayloadAccountSet includes the requested fields of the GraphQL type AccountSet.
type accountSetMemberAccountSetCreateAddToAccountSetAddToAccountSetPayloadAccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns accountSetMemberAccountSetCreateAddToAccountSetAddToAccountSetPayloadAccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *accountSetMemberAccountSetCreateAddToAccountSetAddToAccountSetPayloadAccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// accountSetMemberAccountSetCreateResponse is returned by accountSetMemberAccountSetCreate on success.
type accountSetMemberAccountSetCreateResponse struct {
	AddToAccountSet accountSetMemberAccountSetCreateAddToAccountSetAddToAccountSetPayload `json:"addToAccountSet"`
}

// GetAddToAccountSet returns accountSetMemberAccountSetCreateResponse.AddToAccountSet, and is useful for accessing the field via an interface.
func (v *accountSetMemberAccountSetCreateResponse) GetAddToAccountSet() accountSetMemberAccountSetCreateAddToAccountSetAddToAccountSetPayload {
	return v.AddToAccountSet
}

// accountSetMemberAccountSetRemoveRemoveFromAccountSetRemoveFromAccountSetPayload includes the requested fields of the GraphQL type RemoveFromAccountSetPayload.
type accountSetMemberAccountSetRemoveRemoveFromAccountSetRemoveFromAccountSetPayload struct {
	AccountSet accountSetMemberAccountSetRemoveRemoveFromAccountSetRemoveFromAccountSetPayloadAccountSet `json:"accountSet"`
}

// GetAccountSet returns accountSetMemberAccountSetRemoveRemoveFromAccountSetRemoveFromAccountSetPayload.AccountSet, and is useful for accessing the field via an interface.
func (v *accountSetMemberAccountSetRemoveRemoveFromAccountSetRemoveFromAccountSetPayload) GetAccountSet() accountSetMemberAccountSetRemoveRemoveFromAccountSetRemoveFromAccountSetPayloadAccountSet {
	return v.AccountSet
}

// accountSetMemberAccountSetRemoveRemoveFromAccountSetRemoveFromAccountSetPayloadAccountSet includes the requested fields of the GraphQL type AccountSet.
type accountSetMemberAccountSetRemoveRemoveFromAccountSetRemoveFromAccountSetPayloadAccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns accountSetMemberAccountSetRemoveRemoveFromAccountSetRemoveFromAccountSetPayloadAccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *accountSetMemberAccountSetRemoveRemoveFromAccountSetRemoveFromAccountSetPayloadAccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// accountSetMemberAccountSetRemoveResponse is returned by accountSetMemberAccountSetRemove on success.
type accountSetMemberAccountSetRemoveResponse struct {
	RemoveFromAccountSet accountSetMemberAccountSetRemoveRemoveFromAccountSetRemoveFromAccountSetPayload `json:"removeFromAccountSet"`
}

// GetRemoveFromAccountSet returns accountSetMemberAccountSetRemoveResponse.RemoveFromAccountSet, and is useful for accessing the field via an interface.
func (v *accountSetMemberAccountSetRemoveResponse) GetRemoveFromAccountSet() accountSetMemberAccountSetRemoveRemoveFromAccountSetRemoveFromAccountSetPayload {
	return v.RemoveFromAccountSet
}

// balanceSheetCreateBalanceSheetBalanceSheetMutation includes the requested fields of the GraphQL type BalanceSheetMutation.
type balanceSheetCreateBalanceSheetBalanceSheetMutation struct {
	Create balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayload `json:"create"`
}

// GetCreate returns balanceSheetCreateBalanceSheetBalanceSheetMutation.Create, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutation) GetCreate() balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayload {
	return v.Create
}

// balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayload includes the requested fields of the GraphQL type BalanceSheetCreatePayload.
type balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayload struct {
	BalanceSheet balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet `json:"balanceSheet"`
}

// GetBalanceSheet returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayload.BalanceSheet, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayload) GetBalanceSheet() balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet {
	return v.BalanceSheet
}

// balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet includes the requested fields of the GraphQL type BalanceSheet.
type balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet struct {
	Assets      balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetAssetsAccountSet      `json:"assets"`
	Liabilities balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetLiabilitiesAccountSet `json:"liabilities"`
	Equity      balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetEquityAccountSet      `json:"equity"`
	Schedule1   balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule1AccountSet   `json:"schedule1"`
	Schedule2   balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule2AccountSet   `json:"schedule2"`
	Schedule3   balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule3AccountSet   `json:"schedule3"`
	Schedule4   balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule4AccountSet   `json:"schedule4"`
	Schedule5   balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule5AccountSet   `json:"schedule5"`
	Schedule6   balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule6AccountSet   `json:"schedule6"`
	Schedule7   balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule7AccountSet   `json:"schedule7"`
	Schedule8   balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule8AccountSet   `json:"schedule8"`
	Schedule9   balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule9AccountSet   `json:"schedule9"`
	Schedule10  balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule10AccountSet  `json:"schedule10"`
	Schedule11  balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule11AccountSet  `json:"schedule11"`
	Schedule12  balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule12AccountSet  `json:"schedule12"`
}

// GetAssets returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet.Assets, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet) GetAssets() balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetAssetsAccountSet {
	return v.Assets
}

// GetLiabilities returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet.Liabilities, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet) GetLiabilities() balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetLiabilitiesAccountSet {
	return v.Liabilities
}

// GetEquity returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet.Equity, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet) GetEquity() balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetEquityAccountSet {
	return v.Equity
}

// GetSchedule1 returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet.Schedule1, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet) GetSchedule1() balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule1AccountSet {
	return v.Schedule1
}

// GetSchedule2 returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet.Schedule2, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet) GetSchedule2() balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule2AccountSet {
	return v.Schedule2
}

// GetSchedule3 returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet.Schedule3, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet) GetSchedule3() balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule3AccountSet {
	return v.Schedule3
}

// GetSchedule4 returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet.Schedule4, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet) GetSchedule4() balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule4AccountSet {
	return v.Schedule4
}

// GetSchedule5 returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet.Schedule5, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet) GetSchedule5() balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule5AccountSet {
	return v.Schedule5
}

// GetSchedule6 returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet.Schedule6, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet) GetSchedule6() balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule6AccountSet {
	return v.Schedule6
}

// GetSchedule7 returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet.Schedule7, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet) GetSchedule7() balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule7AccountSet {
	return v.Schedule7
}

// GetSchedule8 returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet.Schedule8, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet) GetSchedule8() balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule8AccountSet {
	return v.Schedule8
}

// GetSchedule9 returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet.Schedule9, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet) GetSchedule9() balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule9AccountSet {
	return v.Schedule9
}

// GetSchedule10 returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet.Schedule10, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet) GetSchedule10() balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule10AccountSet {
	return v.Schedule10
}

// GetSchedule11 returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet.Schedule11, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet) GetSchedule11() balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule11AccountSet {
	return v.Schedule11
}

// GetSchedule12 returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet.Schedule12, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheet) GetSchedule12() balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule12AccountSet {
	return v.Schedule12
}

// balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetAssetsAccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetAssetsAccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetAssetsAccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetAssetsAccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetEquityAccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetEquityAccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetEquityAccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetEquityAccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetLiabilitiesAccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetLiabilitiesAccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetLiabilitiesAccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetLiabilitiesAccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule10AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule10AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule10AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule10AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule11AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule11AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule11AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule11AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule12AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule12AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule12AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule12AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule1AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule1AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule1AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule1AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule2AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule2AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule2AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule2AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule3AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule3AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule3AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule3AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule4AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule4AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule4AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule4AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule5AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule5AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule5AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule5AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule6AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule6AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule6AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule6AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule7AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule7AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule7AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule7AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule8AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule8AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule8AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule8AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule9AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule9AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule9AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateBalanceSheetBalanceSheetMutationCreateBalanceSheetCreatePayloadBalanceSheetSchedule9AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetCreateResponse is returned by balanceSheetCreate on success.
type balanceSheetCreateResponse struct {
	BalanceSheet balanceSheetCreateBalanceSheetBalanceSheetMutation `json:"balanceSheet"`
}

// GetBalanceSheet returns balanceSheetCreateResponse.BalanceSheet, and is useful for accessing the field via an interface.
func (v *balanceSheetCreateResponse) GetBalanceSheet() balanceSheetCreateBalanceSheetBalanceSheetMutation {
	return v.BalanceSheet
}

// balanceSheetGetBalanceSheetBalanceSheetQuery includes the requested fields of the GraphQL type BalanceSheetQuery.
type balanceSheetGetBalanceSheetBalanceSheetQuery struct {
	ByJournalId *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet `json:"byJournalId"`
}

// GetByJournalId returns balanceSheetGetBalanceSheetBalanceSheetQuery.ByJournalId, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQuery) GetByJournalId() *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet {
	return v.ByJournalId
}

// balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet includes the requested fields of the GraphQL type BalanceSheet.
type balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet struct {
	Liabilities balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetLiabilitiesAccountSet `json:"liabilities"`
	Equity      balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetEquityAccountSet      `json:"equity"`
	Assets      balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetAssetsAccountSet      `json:"assets"`
	Schedule1   balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule1AccountSet   `json:"schedule1"`
	Schedule2   balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule2AccountSet   `json:"schedule2"`
	Schedule3   balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule3AccountSet   `json:"schedule3"`
	Schedule4   balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule4AccountSet   `json:"schedule4"`
	Schedule5   balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule5AccountSet   `json:"schedule5"`
	Schedule6   balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule6AccountSet   `json:"schedule6"`
	Schedule7   balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule7AccountSet   `json:"schedule7"`
	Schedule8   balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule8AccountSet   `json:"schedule8"`
	Schedule9   balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule9AccountSet   `json:"schedule9"`
	Schedule10  balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule10AccountSet  `json:"schedule10"`
	Schedule11  balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule11AccountSet  `json:"schedule11"`
	Schedule12  balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule12AccountSet  `json:"schedule12"`
}

// GetLiabilities returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet.Liabilities, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet) GetLiabilities() balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetLiabilitiesAccountSet {
	return v.Liabilities
}

// GetEquity returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet.Equity, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet) GetEquity() balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetEquityAccountSet {
	return v.Equity
}

// GetAssets returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet.Assets, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet) GetAssets() balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetAssetsAccountSet {
	return v.Assets
}

// GetSchedule1 returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet.Schedule1, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet) GetSchedule1() balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule1AccountSet {
	return v.Schedule1
}

// GetSchedule2 returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet.Schedule2, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet) GetSchedule2() balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule2AccountSet {
	return v.Schedule2
}

// GetSchedule3 returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet.Schedule3, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet) GetSchedule3() balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule3AccountSet {
	return v.Schedule3
}

// GetSchedule4 returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet.Schedule4, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet) GetSchedule4() balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule4AccountSet {
	return v.Schedule4
}

// GetSchedule5 returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet.Schedule5, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet) GetSchedule5() balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule5AccountSet {
	return v.Schedule5
}

// GetSchedule6 returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet.Schedule6, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet) GetSchedule6() balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule6AccountSet {
	return v.Schedule6
}

// GetSchedule7 returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet.Schedule7, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet) GetSchedule7() balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule7AccountSet {
	return v.Schedule7
}

// GetSchedule8 returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet.Schedule8, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet) GetSchedule8() balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule8AccountSet {
	return v.Schedule8
}

// GetSchedule9 returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet.Schedule9, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet) GetSchedule9() balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule9AccountSet {
	return v.Schedule9
}

// GetSchedule10 returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet.Schedule10, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet) GetSchedule10() balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule10AccountSet {
	return v.Schedule10
}

// GetSchedule11 returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet.Schedule11, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet) GetSchedule11() balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule11AccountSet {
	return v.Schedule11
}

// GetSchedule12 returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet.Schedule12, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheet) GetSchedule12() balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule12AccountSet {
	return v.Schedule12
}

// balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetAssetsAccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetAssetsAccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetAssetsAccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetAssetsAccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetEquityAccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetEquityAccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetEquityAccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetEquityAccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetLiabilitiesAccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetLiabilitiesAccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetLiabilitiesAccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetLiabilitiesAccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule10AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule10AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule10AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule10AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule11AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule11AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule11AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule11AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule12AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule12AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule12AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule12AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule1AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule1AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule1AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule1AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule2AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule2AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule2AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule2AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule3AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule3AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule3AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule3AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule4AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule4AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule4AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule4AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule5AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule5AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule5AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule5AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule6AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule6AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule6AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule6AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule7AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule7AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule7AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule7AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule8AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule8AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule8AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule8AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule9AccountSet includes the requested fields of the GraphQL type AccountSet.
type balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule9AccountSet struct {
	AccountSetId string `json:"accountSetId"`
}

// GetAccountSetId returns balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule9AccountSet.AccountSetId, and is useful for accessing the field via an interface.
func (v *balanceSheetGetBalanceSheetBalanceSheetQueryByJournalIdBalanceSheetSchedule9AccountSet) GetAccountSetId() string {
	return v.AccountSetId
}

// balanceSheetGetResponse is returned by balanceSheetGet on success.
type balanceSheetGetResponse struct {
	BalanceSheet balanceSheetGetBalanceSheetBalanceSheetQuery `json:"balanceSheet"`
}

// GetBalanceSheet returns balanceSheetGetResponse.BalanceSheet, and is useful for accessing the field via an interface.
func (v *balanceSheetGetResponse) GetBalanceSheet() balanceSheetGetBalanceSheetBalanceSheetQuery {
	return v.BalanceSheet
}

// bfxIntegrationCreateBitfinexBitfinexMutation includes the requested fields of the GraphQL type BitfinexMutation.
type bfxIntegrationCreateBitfinexBitfinexMutation struct {
	IntegrationCreate bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayload `json:"integrationCreate"`
}

// GetIntegrationCreate returns bfxIntegrationCreateBitfinexBitfinexMutation.IntegrationCreate, and is useful for accessing the field via an interface.
func (v *bfxIntegrationCreateBitfinexBitfinexMutation) GetIntegrationCreate() bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayload {
	return v.IntegrationCreate
}

// bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayload includes the requested fields of the GraphQL type BfxIntegrationCreatePayload.
type bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayload struct {
	Integration bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayloadIntegrationBfxIntegration `json:"integration"`
}

// GetIntegration returns bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayload.Integration, and is useful for accessing the field via an interface.
func (v *bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayload) GetIntegration() bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayloadIntegrationBfxIntegration {
	return v.Integration
}

// bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayloadIntegrationBfxIntegration includes the requested fields of the GraphQL type BfxIntegration.
type bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayloadIntegrationBfxIntegration struct {
	IntegrationId    string  `json:"integrationId"`
	Name             string  `json:"name"`
	Description      *string `json:"description"`
	OmnibusAccountId string  `json:"omnibusAccountId"`
}

// GetIntegrationId returns bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayloadIntegrationBfxIntegration.IntegrationId, and is useful for accessing the field via an interface.
func (v *bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayloadIntegrationBfxIntegration) GetIntegrationId() string {
	return v.IntegrationId
}

// GetName returns bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayloadIntegrationBfxIntegration.Name, and is useful for accessing the field via an interface.
func (v *bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayloadIntegrationBfxIntegration) GetName() string {
	return v.Name
}

// GetDescription returns bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayloadIntegrationBfxIntegration.Description, and is useful for accessing the field via an interface.
func (v *bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayloadIntegrationBfxIntegration) GetDescription() *string {
	return v.Description
}

// GetOmnibusAccountId returns bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayloadIntegrationBfxIntegration.OmnibusAccountId, and is useful for accessing the field via an interface.
func (v *bfxIntegrationCreateBitfinexBitfinexMutationIntegrationCreateBfxIntegrationCreatePayloadIntegrationBfxIntegration) GetOmnibusAccountId() string {
	return v.OmnibusAccountId
}

// bfxIntegrationCreateResponse is returned by bfxIntegrationCreate on success.
type bfxIntegrationCreateResponse struct {
	Bitfinex bfxIntegrationCreateBitfinexBitfinexMutation `json:"bitfinex"`
}

// GetBitfinex returns bfxIntegrationCreateResponse.Bitfinex, and is useful for accessing the field via an interface.
func (v *bfxIntegrationCreateResponse) GetBitfinex() bfxIntegrationCreateBitfinexBitfinexMutation {
	return v.Bitfinex
}

// bfxIntegrationGetBitfinexBitfinexQuery includes the requested fields of the GraphQL type BitfinexQuery.
type bfxIntegrationGetBitfinexBitfinexQuery struct {
	Integration *bfxIntegrationGetBitfinexBitfinexQueryIntegrationBfxIntegration `json:"integration"`
}

// GetIntegration returns bfxIntegrationGetBitfinexBitfinexQuery.Integration, and is useful for accessing the field via an interface.
func (v *bfxIntegrationGetBitfinexBitfinexQuery) GetIntegration() *bfxIntegrationGetBitfinexBitfinexQueryIntegrationBfxIntegration {
	return v.Integration
}

// bfxIntegrationGetBitfinexBitfinexQueryIntegrationBfxIntegration includes the requested fields of the GraphQL type BfxIntegration.
type bfxIntegrationGetBitfinexBitfinexQueryIntegrationBfxIntegration struct {
	IntegrationId    string  `json:"integrationId"`
	Name             string  `json:"name"`
	Description      *string `json:"description"`
	OmnibusAccountId string  `json:"omnibusAccountId"`
}

// GetIntegrationId returns bfxIntegrationGetBitfinexBitfinexQueryIntegrationBfxIntegration.IntegrationId, and is useful for accessing the field via an interface.
func (v *bfxIntegrationGetBitfinexBitfinexQueryIntegrationBfxIntegration) GetIntegrationId() string {
	return v.IntegrationId
}

// GetName returns bfxIntegrationGetBitfinexBitfinexQueryIntegrationBfxIntegration.Name, and is useful for accessing the field via an interface.
func (v *bfxIntegrationGetBitfinexBitfinexQueryIntegrationBfxIntegration) GetName() string {
	return v.Name
}

// GetDescription returns bfxIntegrationGetBitfinexBitfinexQueryIntegrationBfxIntegration.Description, and is useful for accessing the field via an interface.
func (v *bfxIntegrationGetBitfinexBitfinexQueryIntegrationBfxIntegration) GetDescription() *string {
	return v.Description
}

// GetOmnibusAccountId returns bfxIntegrationGetBitfinexBitfinexQueryIntegrationBfxIntegration.OmnibusAccountId, and is useful for accessing the field via an interface.
func (v *bfxIntegrationGetBitfinexBitfinexQueryIntegrationBfxIntegration) GetOmnibusAccountId() string {
	return v.OmnibusAccountId
}

// bfxIntegrationGetResponse is returned by bfxIntegrationGet on success.
type bfxIntegrationGetResponse struct {
	Bitfinex bfxIntegrationGetBitfinexBitfinexQuery `json:"bitfinex"`
}

// GetBitfinex returns bfxIntegrationGetResponse.Bitfinex, and is useful for accessing the field via an interface.
func (v *bfxIntegrationGetResponse) GetBitfinex() bfxIntegrationGetBitfinexBitfinexQuery {
	return v.Bitfinex
}

// journalCreateJournalCreateJournalCreatePayload includes the requested fields of the GraphQL type JournalCreatePayload.
type journalCreateJournalCreateJournalCreatePayload struct {
	Journal journalCreateJournalCreateJournalCreatePayloadJournal `json:"journal"`
}

// GetJournal returns journalCreateJournalCreateJournalCreatePayload.Journal, and is useful for accessing the field via an interface.
func (v *journalCreateJournalCreateJournalCreatePayload) GetJournal() journalCreateJournalCreateJournalCreatePayloadJournal {
	return v.Journal
}

// journalCreateJournalCreateJournalCreatePayloadJournal includes the requested fields of the GraphQL type Journal.
type journalCreateJournalCreateJournalCreatePayloadJournal struct {
	JournalId   string  `json:"journalId"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Status      Status  `json:"status"`
}

// GetJournalId returns journalCreateJournalCreateJournalCreatePayloadJournal.JournalId, and is useful for accessing the field via an interface.
func (v *journalCreateJournalCreateJournalCreatePayloadJournal) GetJournalId() string {
	return v.JournalId
}

// GetName returns journalCreateJournalCreateJournalCreatePayloadJournal.Name, and is useful for accessing the field via an interface.
func (v *journalCreateJournalCreateJournalCreatePayloadJournal) GetName() string { return v.Name }

// GetDescription returns journalCreateJournalCreateJournalCreatePayloadJournal.Description, and is useful for accessing the field via an interface.
func (v *journalCreateJournalCreateJournalCreatePayloadJournal) GetDescription() *string {
	return v.Description
}

// GetStatus returns journalCreateJournalCreateJournalCreatePayloadJournal.Status, and is useful for accessing the field via an interface.
func (v *journalCreateJournalCreateJournalCreatePayloadJournal) GetStatus() Status { return v.Status }

// journalCreateResponse is returned by journalCreate on success.
type journalCreateResponse struct {
	JournalCreate journalCreateJournalCreateJournalCreatePayload `json:"journalCreate"`
}

// GetJournalCreate returns journalCreateResponse.JournalCreate, and is useful for accessing the field via an interface.
func (v *journalCreateResponse) GetJournalCreate() journalCreateJournalCreateJournalCreatePayload {
	return v.JournalCreate
}

// The query or mutation executed by accountCreate.
const accountCreate_Operation = `
mutation accountCreate ($input: AccountCreateInput!) {
	accountCreate(input: $input) {
		account {
			accountId
			code
			name
			normalBalanceType
			status
			externalId
			description
			metadata
		}
	}
}
`

func accountCreate(
	ctx_ context.Context,
	client_ graphql.Client,
	input AccountCreateInput,
) (*accountCreateResponse, error) {
	req_ := &graphql.Request{
		OpName: "accountCreate",
		Query:  accountCreate_Operation,
		Variables: &__accountCreateInput{
			Input: input,
		},
	}
	var err_ error

	var data_ accountCreateResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by accountGet.
const accountGet_Operation = `
query accountGet ($id: UUID!) {
	account(id: $id) {
		accountId
		name
		description
		status
		metadata
		code
		normalBalanceType
		externalId
		sets(first: 10) {
			nodes {
				accountSetId
			}
		}
	}
}
`

func accountGet(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (*accountGetResponse, error) {
	req_ := &graphql.Request{
		OpName: "accountGet",
		Query:  accountGet_Operation,
		Variables: &__accountGetInput{
			Id: id,
		},
	}
	var err_ error

	var data_ accountGetResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by accountSetCreate.
const accountSetCreate_Operation = `
mutation accountSetCreate ($input: AccountSetCreateInput!) {
	accountSetCreate(input: $input) {
		accountSet {
			accountSetId
			journalId
			name
			normalBalanceType
			description
			metadata
		}
	}
}
`

func accountSetCreate(
	ctx_ context.Context,
	client_ graphql.Client,
	input AccountSetCreateInput,
) (*accountSetCreateResponse, error) {
	req_ := &graphql.Request{
		OpName: "accountSetCreate",
		Query:  accountSetCreate_Operation,
		Variables: &__accountSetCreateInput{
			Input: input,
		},
	}
	var err_ error

	var data_ accountSetCreateResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by accountSetGet.
const accountSetGet_Operation = `
query accountSetGet ($id: UUID!) {
	accountSet(id: $id) {
		accountSetId
		journalId
		name
		description
		normalBalanceType
	}
}
`

func accountSetGet(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (*accountSetGetResponse, error) {
	req_ := &graphql.Request{
		OpName: "accountSetGet",
		Query:  accountSetGet_Operation,
		Variables: &__accountSetGetInput{
			Id: id,
		},
	}
	var err_ error

	var data_ accountSetGetResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by accountSetMemberAccountCreate.
const accountSetMemberAccountCreate_Operation = `
mutation accountSetMemberAccountCreate ($accountSetId: UUID!, $accountId: UUID!) {
	addToAccountSet(input: {accountSetId:$accountSetId,memberId:$accountId,memberType:ACCOUNT}) {
		accountSet {
			accountSetId
		}
	}
}
`

func accountSetMemberAccountCreate(
	ctx_ context.Context,
	client_ graphql.Client,
	accountSetId string,
	accountId string,
) (*accountSetMemberAccountCreateResponse, error) {
	req_ := &graphql.Request{
		OpName: "accountSetMemberAccountCreate",
		Query:  accountSetMemberAccountCreate_Operation,
		Variables: &__accountSetMemberAccountCreateInput{
			AccountSetId: accountSetId,
			AccountId:    accountId,
		},
	}
	var err_ error

	var data_ accountSetMemberAccountCreateResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by accountSetMemberAccountRemove.
const accountSetMemberAccountRemove_Operation = `
mutation accountSetMemberAccountRemove ($accountSetId: UUID!, $accountId: UUID!) {
	removeFromAccountSet(input: {accountSetId:$accountSetId,memberId:$accountId,memberType:ACCOUNT}) {
		accountSet {
			accountSetId
		}
	}
}
`

func accountSetMemberAccountRemove(
	ctx_ context.Context,
	client_ graphql.Client,
	accountSetId string,
	accountId string,
) (*accountSetMemberAccountRemoveResponse, error) {
	req_ := &graphql.Request{
		OpName: "accountSetMemberAccountRemove",
		Query:  accountSetMemberAccountRemove_Operation,
		Variables: &__accountSetMemberAccountRemoveInput{
			AccountSetId: accountSetId,
			AccountId:    accountId,
		},
	}
	var err_ error

	var data_ accountSetMemberAccountRemoveResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by accountSetMemberAccountSetCreate.
const accountSetMemberAccountSetCreate_Operation = `
mutation accountSetMemberAccountSetCreate ($accountSetId: UUID!, $memberAccountSetId: UUID!) {
	addToAccountSet(input: {accountSetId:$accountSetId,memberId:$memberAccountSetId,memberType:ACCOUNT_SET}) {
		accountSet {
			accountSetId
		}
	}
}
`

func accountSetMemberAccountSetCreate(
	ctx_ context.Context,
	client_ graphql.Client,
	accountSetId string,
	memberAccountSetId string,
) (*accountSetMemberAccountSetCreateResponse, error) {
	req_ := &graphql.Request{
		OpName: "accountSetMemberAccountSetCreate",
		Query:  accountSetMemberAccountSetCreate_Operation,
		Variables: &__accountSetMemberAccountSetCreateInput{
			AccountSetId:       accountSetId,
			MemberAccountSetId: memberAccountSetId,
		},
	}
	var err_ error

	var data_ accountSetMemberAccountSetCreateResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by accountSetMemberAccountSetRemove.
const accountSetMemberAccountSetRemove_Operation = `
mutation accountSetMemberAccountSetRemove ($accountSetId: UUID!, $memberAccountSetId: UUID!) {
	removeFromAccountSet(input: {accountSetId:$accountSetId,memberId:$memberAccountSetId,memberType:ACCOUNT_SET}) {
		accountSet {
			accountSetId
		}
	}
}
`

func accountSetMemberAccountSetRemove(
	ctx_ context.Context,
	client_ graphql.Client,
	accountSetId string,
	memberAccountSetId string,
) (*accountSetMemberAccountSetRemoveResponse, error) {
	req_ := &graphql.Request{
		OpName: "accountSetMemberAccountSetRemove",
		Query:  accountSetMemberAccountSetRemove_Operation,
		Variables: &__accountSetMemberAccountSetRemoveInput{
			AccountSetId:       accountSetId,
			MemberAccountSetId: memberAccountSetId,
		},
	}
	var err_ error

	var data_ accountSetMemberAccountSetRemoveResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by balanceSheetCreate.
const balanceSheetCreate_Operation = `
mutation balanceSheetCreate ($input: BalanceSheetCreateInput!) {
	balanceSheet {
		create(input: $input) {
			balanceSheet {
				assets {
					accountSetId
				}
				liabilities {
					accountSetId
				}
				equity {
					accountSetId
				}
				schedule1 {
					accountSetId
				}
				schedule2 {
					accountSetId
				}
				schedule3 {
					accountSetId
				}
				schedule4 {
					accountSetId
				}
				schedule5 {
					accountSetId
				}
				schedule6 {
					accountSetId
				}
				schedule7 {
					accountSetId
				}
				schedule8 {
					accountSetId
				}
				schedule9 {
					accountSetId
				}
				schedule10 {
					accountSetId
				}
				schedule11 {
					accountSetId
				}
				schedule12 {
					accountSetId
				}
			}
		}
	}
}
`

func balanceSheetCreate(
	ctx_ context.Context,
	client_ graphql.Client,
	input BalanceSheetCreateInput,
) (*balanceSheetCreateResponse, error) {
	req_ := &graphql.Request{
		OpName: "balanceSheetCreate",
		Query:  balanceSheetCreate_Operation,
		Variables: &__balanceSheetCreateInput{
			Input: input,
		},
	}
	var err_ error

	var data_ balanceSheetCreateResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by balanceSheetGet.
const balanceSheetGet_Operation = `
query balanceSheetGet ($journalId: UUID!) {
	balanceSheet {
		byJournalId(journalId: $journalId) {
			liabilities {
				accountSetId
			}
			equity {
				accountSetId
			}
			assets {
				accountSetId
			}
			schedule1 {
				accountSetId
			}
			schedule2 {
				accountSetId
			}
			schedule3 {
				accountSetId
			}
			schedule4 {
				accountSetId
			}
			schedule5 {
				accountSetId
			}
			schedule6 {
				accountSetId
			}
			schedule7 {
				accountSetId
			}
			schedule8 {
				accountSetId
			}
			schedule9 {
				accountSetId
			}
			schedule10 {
				accountSetId
			}
			schedule11 {
				accountSetId
			}
			schedule12 {
				accountSetId
			}
		}
	}
}
`

func balanceSheetGet(
	ctx_ context.Context,
	client_ graphql.Client,
	journalId string,
) (*balanceSheetGetResponse, error) {
	req_ := &graphql.Request{
		OpName: "balanceSheetGet",
		Query:  balanceSheetGet_Operation,
		Variables: &__balanceSheetGetInput{
			JournalId: journalId,
		},
	}
	var err_ error

	var data_ balanceSheetGetResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by bfxIntegrationCreate.
const bfxIntegrationCreate_Operation = `
mutation bfxIntegrationCreate ($input: BfxIntegrationCreateInput!) {
	bitfinex {
		integrationCreate(input: $input) {
			integration {
				integrationId
				name
				description
				omnibusAccountId
			}
		}
	}
}
`

func bfxIntegrationCreate(
	ctx_ context.Context,
	client_ graphql.Client,
	input BfxIntegrationCreateInput,
) (*bfxIntegrationCreateResponse, error) {
	req_ := &graphql.Request{
		OpName: "bfxIntegrationCreate",
		Query:  bfxIntegrationCreate_Operation,
		Variables: &__bfxIntegrationCreateInput{
			Input: input,
		},
	}
	var err_ error

	var data_ bfxIntegrationCreateResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by bfxIntegrationGet.
const bfxIntegrationGet_Operation = `
query bfxIntegrationGet ($id: UUID!) {
	bitfinex {
		integration(id: $id) {
			integrationId
			name
			description
			omnibusAccountId
		}
	}
}
`

func bfxIntegrationGet(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (*bfxIntegrationGetResponse, error) {
	req_ := &graphql.Request{
		OpName: "bfxIntegrationGet",
		Query:  bfxIntegrationGet_Operation,
		Variables: &__bfxIntegrationGetInput{
			Id: id,
		},
	}
	var err_ error

	var data_ bfxIntegrationGetResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by journalCreate.
const journalCreate_Operation = `
mutation journalCreate ($input: JournalCreateInput!) {
	journalCreate(input: $input) {
		journal {
			journalId
			name
			description
			status
		}
	}
}
`

func journalCreate(
	ctx_ context.Context,
	client_ graphql.Client,
	input JournalCreateInput,
) (*journalCreateResponse, error) {
	req_ := &graphql.Request{
		OpName: "journalCreate",
		Query:  journalCreate_Operation,
		Variables: &__journalCreateInput{
			Input: input,
		},
	}
	var err_ error

	var data_ journalCreateResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
